baseurl = "https://joybaltimore.netlify.app/"
languageCode = "en-us"
title = "J.O.Y. Baltimore"
theme = "castanet"
googleAnalytics = ""
paginate = "9"


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Books"
    identifier = "books"
    url = "/books"
    parent = "resources"
[[Menu.Main]]
    name = "Podcasts"
    identifier = "podcasts"
    url = "/books"
    parent = "resources"

[params]
mainSections = ["episode"]
site_theme = "grey"
# site_layout = "grid"
site_layout = "row"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
about_logo = "img/jb_logo.jpg"
copyright_notice = "Copyright 2020 J.O.Y. Baltimore"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "J.O.Y. Baltimore is one of the few LGBTQ+ organizations dedicated to servicing homeless and runaway youth in the greater Baltimore City Area."
media_prefix = "https://www.facebook.com/joybaltimore"
  [params.feed]
    copyright = "Copyright 2020 J.O.Y. Baltimore" #do not use markdown in this field; it is used in the feed
    itunes_author = "Lonnie Walker" #no markdown or HTML
    itunes_summary = "J.O.Y. Baltimore is one of the few LGBTQ+ organizations servicing homeless and runaway youth." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Lonnie Walker"
    itunes_owner_email = "lwalker@joybaltimore.org" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "jb_logo.jpg" #fqdn to the image art for your podcast
    itunes_top_category = "LGBTQ+ Youth"
    language = "en-us"

  [params.podlove] # https://subscribe-button.podlove.org
    subscribe_title = ""              # fallback: site title from above
    subscribe_subtitle = ""           # fallback: ""
    subscribe_description = ""        # fallback: ""
    subscribe_cover = "img/logo.jpg"  # fallback: ""
    subscribe_color = "#585e6c"       # fallback: ""
    subscribe_size = "medium"         # options: small, medium, big
    subscribe_format = "rectangle"    # options: rectangle, square, cover
    subscribe_style = "filled"        # options: filled, outline, frameless
    subscribe_language = "de"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
    subscribe_feed_type = "audio"     # options: audio, video
    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    twitter_domain = "joybaltimore.netlify.app" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus = "ArrestedDevOps"

  [params.authors]
    [params.authors.Marcus]
      name	= "Marcus Henry"
      thumbnail = "img/host/mhenrey1.jpg"
      bio = "Marcus Henry is a cutie batootie."
    [params.authors.Sakichi]
			name = "Sakichi Hiyashi"
			thumbnail = "img/host/sakih.jpg"
			bio = "Sakichi Hiyashi loves to play video games."
    [params.authors.Lonnie]
      name = "Lonnie Walker"
      thumbnail = "img/host/lwalker_edit.jpg"
      bio = "Lonnie Walker is the GOAT, period."

    [params.links]
      [params.links.jb]
        name = "JOY Baltimore"
        url = "https://www.facebook.com/profile.php?id=100016693456285"
        
